# .github/workflows/bump-version.yml
name: Bump version on main pushes

on:
  push:
    branches: [ main ]
    paths: [ pepy_stats/** ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bump:
    # Avoid infinite loop when the bot pushes the bump commit
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry 2.x and add to PATH
        run: |
          pipx install "poetry==2.*"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          poetry --version

      - name: Bump patch version with Poetry
        run: |
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"   # ensure poetry on PATH
          poetry --version
          echo "Before: $(poetry version --short || true)"
          poetry version patch
          echo "After:  $(poetry version --short || true)"
          git status --porcelain

      - name: Commit & push pyproject.toml if changed
        id: commit
        run: |
          if git diff --quiet -- pyproject.toml; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
            echo "No version change; skipping commit."
            exit 0
          fi
          git config user.name  "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add pyproject.toml
          git commit -m "chore: bump version (patch)"
          git push
          echo "changed=true" >> "$GITHUB_OUTPUT"

      - name: Tag version (no v prefix)
        if: steps.commit.outputs.changed == 'true'
        run: |
          # Make sure we see existing tags before creating a new one
          git fetch --tags --force
          VER=$(poetry version --short)
          if git rev-parse -q --verify "refs/tags/$VER" >/dev/null; then
            echo "Tag $VER already exists; skipping."
            exit 0
          fi
          git tag "$VER"
          git push origin "$VER"