# .github/workflows/update-and-publish.yml
name: Update package stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pepy-stats CLI
        run: |
          python -m pip install --upgrade pip
          pip install "git+https://github.com/michaelthomasletts/pepy-stats.git"

      - name: Run pepy-stats
        env:
          PEPY_API_KEY: ${{ secrets.PEPY_API_KEY }}
        run: |
          pepy-stats boto3-refresh-session laudanum profile-this -k "$PEPY_API_KEY"

      - name: Install Poetry 2.x and add to PATH
        run: |
          pipx install "poetry==2.*"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Bump version (patch) with Poetry
        run: |
          poetry --version
          echo "Before: $(poetry version --short || true)"
          poetry version patch
          echo "After:  $(poetry version --short || true)"

      - name: Commit & push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: refresh Pepy badges & bump version (patch)"
          file_pattern: |
            stats/*.json
            pyproject.toml

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: stats

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
