# .github/workflows/update-stats.yml
name: Update package stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'   # daily 08:00 UTC

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pepy-stats CLI
        run: |
          python -m pip install --upgrade pip
          pip install "git+https://github.com/michaelthomasletts/pepy-stats.git"

      - name: Run pepy-stats
        env:
          PEPY_API_KEY: ${{ secrets.PEPY_API_KEY }}
        run: |
          pepy-stats boto3-refresh-session laudanum profile-this -k "$PEPY_API_KEY"

      - name: Commit & push stats if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(stats): refresh PePy badges"
          file_pattern: "stats/*.json"

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: stats

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
